--- #YAML:1.0
name:                Net-DNSBL-Statistics
version:             0.09
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::DNS::Codes:               0.09
    Net::DNS::ToolKit:             0.41
    Net::DNSBL::MultiDaemon:       0.24
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
